spring:
  application:
    name: wedding-invitation

  # Настройки подключения к Yandex Database (YDB)
  datasource:
    # URL вашей БД (замените на свой из консоли Yandex Cloud)
    # Переменная SA_KEY_FILE_PATH указывает на путь к JSON-ключу сервисного аккаунта внутри контейнера
    url: ${YDB_URL}&useMetadata=true
    driver-class-name: tech.ydb.jdbc.YdbDriver

  # Настройки JPA и Hibernate под YDB
  jpa:
    properties:
      hibernate:
        dialect: tech.ydb.hibernate.dialect.YdbDialect
    hibernate:
      ddl-auto: update

  # Настройки шаблонизатора Thymeleaf
  thymeleaf:
    cache: true # Обязательно TRUE для Serverless! Сэкономит оперативную память и ускорит «холодный старт»
    mode: HTML
    encoding: UTF-8

# Настройки логирования
logging:
  level:
    root: info
    org.hibernate.SQL: error # Отключаем логирование SQL в продакшене
