spring:
  application:
    name: wedding-invitation

  # Настройки подключения к Yandex Database (YDB)
  datasource:
    # URL вашей БД (замените на свой из консоли Yandex Cloud)
    # Переменная SA_KEY_FILE_PATH указывает на путь к JSON-ключу сервисного аккаунта внутри контейнера
    url: ${YDB_URL}
    driver-class-name: tech.ydb.jdbc.YdbDriver

  # Настройки JPA и Hibernate под YDB
  jpa:
    hibernate:
      # Для YDB безопасно оставить update, но Hibernate создаст таблицы только при первом запуске
      ddl-auto: update
    properties:
      hibernate:
        # Указываем специальный диалект для работы с синтаксисом YDB
        dialect: tech.ydb.dialect.YdbDialect
        show_sql: false     # Отключаем в проде, чтобы не засорять логи Яндекса
        format_sql: false
      ydb:
        saFile: ${YDB_SA_KEY_PATH} # Драйвер сам прочитает и раскодирует Base64 строку
  # Настройки шаблонизатора Thymeleaf
  thymeleaf:
    cache: true # Обязательно TRUE для Serverless! Сэкономит оперативную память и ускорит «холодный старт»
    mode: HTML
    encoding: UTF-8

# Настройки логирования
logging:
  level:
    root: info
    org.hibernate.SQL: error # Отключаем логирование SQL в продакшене
