name: Deploy Spring Boot to Yandex Serverless

on:
  push:
    branches:
      - master # Срабатывает при пуше или слиянии в master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код вашего проекта из GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Собираем JAR-файл проекта через встроенный Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Авторизуемся в Yandex Cloud Container Registry через СТАРЫЙ текстовый JSON
      - name: Yandex Cloud Registry Login
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}

      # 5. Собираем чистый Docker-образ без секретов внутри
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/spring-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # 6. Создаем или обновляем Serverless Container в Yandex Cloud
      - name: Deploy Serverless Container
        uses: yc-actions/yc-sls-container-deploy@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_KEY }}
          container-name: "wedding-inviter-service-app"
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/spring-app:${{ github.sha }}
          revision-cores: 1
          revision-core-fraction: 5
          revision-memory: "2GB"
          revision-service-account-id: ${{ secrets.YC_CONTAINER_SA_ID }}
          revision-env: '["PORT=8080","SPRING_PROFILES_ACTIVE=prod","APP_SECURITY_USERNAME=${{ secrets.APP_SECURITY_USERNAME }}","APP_SECURITY_PASSWORD=${{ secrets.APP_SECURITY_PASSWORD }}","YDB_URL=${{ secrets.YC_YDB_URL }}","YDB_KEY=${{ secrets.YC_YDB_SA_BASE64_KEY }}"]'